### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by katerobsau** [katerobsau/shinySlides#1]
I've come across a weird bug that requires a change being made to the .Rmd file header in order to have the assets display on slides correctly on consecutive builds. I was working around this problem a little while ago (6 months +) and forget yesterday! So I'm opening an issue.

It seems to be a pretty insidious bug. So I will try to create a minimum working exactly to identify the problem and whether it is related to a conflict within my slide code chunks or something else.

**Comment by kcf-jackson** [comment]
The issue has been fixed already! Please see our communication on 22/9/2019 item (b) (iii).

The cause of the problem is that the `runtime` directive in the YAML header should not be indented; when indented, it will appear `NULL` in the `rmarkdown::run()` call.

I didn't update the `examples` folder as I thought you may be using it. Perhaps you can do a pull request (or direct merge if you want)? Thanks.
